### ISSUE TITLE
starFormatted bug

### ISSUE THREAD

**Issue by lem6ns** [lilithmod/unborn-hypixel#1]
![image](https://user-images.githubusercontent.com/62519659/147892168-ded0bdce-33c4-4723-a3a1-5596ba75e609.png)
Fetching the user "momma" & getting starFormatted gives an invalid string

**Comment by nealol** [comment]
Thanks, will fix tonight.

**Comment by nealol** [comment]
> ![image](https://user-images.githubusercontent.com/62519659/147892168-ded0bdce-33c4-4723-a3a1-5596ba75e609.png) Fetching the user "momma" & getting starFormatted gives an invalid string

This has been fixed in the latest commit and will make it into 0.4 at some point.

**Comment by lem6ns** [comment]
Fixed in v0.4.
